# Generated by Django 4.2.9 on 2024-01-30 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('color', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField()),
                ('failures', models.IntegerField()),
                ('currently_running', models.BooleanField()),
                ('L1_voltage', models.FloatField()),
                ('L2_voltage', models.FloatField()),
                ('L3_voltage', models.FloatField()),
                ('input_current_L1', models.FloatField()),
                ('input_current_L2', models.FloatField()),
                ('input_current_L3', models.FloatField()),
                ('AC_freq', models.FloatField()),
                ('output_DC_voltage', models.FloatField()),
                ('total_DC_load_c', models.FloatField()),
                ('total_battery_c', models.FloatField()),
                ('battery_capacity', models.IntegerField()),
                ('remaining_capacity', models.IntegerField()),
                ('remaining_capacity_percenteage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
