# Generated by Django 4.2.9 on 2024-01-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingGETandPOST', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converter',
            name='AC_freq',
        ),
        migrations.RemoveField(
            model_name='converter',
            name='output_DC_voltage',
        ),
        migrations.RemoveField(
            model_name='converter',
            name='total_DC_load_c',
        ),
    ]
