# Generated by Django 4.2.9 on 2024-02-11 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingGETandPOST', '0003_remove_converter_last_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converter',
            name='last_update_date',
        ),
        migrations.RemoveField(
            model_name='converter',
            name='last_update_time',
        ),
        migrations.AddField(
            model_name='converter',
            name='last_update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 6, 14, 16, 427649, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
